.PHONY: FORCE
all: FORCE
	$(MAKE) -C .. vivuscoin_qt test_vivuscoin_qt
clean: FORCE
	$(MAKE) -C .. vivuscoin_qt_clean test_vivuscoin_qt_clean
check: FORCE
	$(MAKE) -C .. test_vivuscoin_qt_check
vivuscoin-qt vivuscoin-qt.exe: FORCE
	 $(MAKE) -C .. vivuscoin_qt
